version: 0.1
# instance: rdu2_mock

base_wattage: 700

products:
  - bm
  - rhos
  - ocp
  - vm

platforms:
  - x86_64
  - ppc64le
  - aarch64

systems:
  - rhel7
  - rhel8
  - fedora35

mock_platforms:
  - name: x86_64
    available: 100
    cpus_per_system: 4
    ram_per_system: 4
  - name: ppc64le
    available: 10
    cpus_per_system: 8
    ram_per_system: 8
  - name: aarch64
    available: 15
    cpus_per_system: 8
    ram_per_system: 2
  - name: s390x
    cpus_per_system: 1
    ram_per_system: 2
    available: 100

mock_products:
  - name: rhos
    available: 30
    cpus_per_system: 16
    ram_per_system: 64
  - name: ocp
    available: 100
    cpus_per_system: 16
    ram_per_system: 64
  - name: rhv
    available: 10
    cpus_per_system: 4
    ram_per_system: 16
