"""
Create bare metal model for PoC

Revision ID: 01129c0eee22
Revises: d0264f75ac84
Create Date: 2022-06-16 15:32:23.291739
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '01129c0eee22'
down_revision = 'd0264f75ac84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bare_metal_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('base_os', sa.Enum('CENTOS', 'FEDORA', 'RED_HAT', name='imagebaseos'), nullable=False),
    sa.Column('type', sa.Enum('GENERIC', 'ISO', 'QCOW2', name='baremetalimagetype'), nullable=False),
    sa.Column('arch', sa.Enum('x86_64', name='baremetalarch'), nullable=False),
    sa.Column('legacy_bios', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('uefi', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('secure_boot', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('arch', 'base_os', 'type', 'version', name='unique_image_constraint')
    )
    op.create_table('bare_metal_handler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.Enum('IRONIC', name='baremetalhandlertype'), nullable=False),
    sa.Column('arch', sa.Enum('x86_64', name='baremetalarch'), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'FAILED_API_CHECK', 'FAILED_SSH_CHECK', 'MAINTENANCE', 'UNAVAILABLE', name='baremetalhandlerstatus'), server_default='UNAVAILABLE', nullable=False),
    sa.Column('last_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_check_error', sa.Text(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_name', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('base_url', sa.String(length=128), nullable=False),
    sa.Column('hostname', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['lab_location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_url')
    )
    op.create_table('bare_metal_image_iso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('download_url', sa.String(length=1024), nullable=False),
    sa.Column('iso_sha256', sa.String(length=64), nullable=False),
    sa.Column('kernel_sub_path', sa.String(length=128), nullable=False),
    sa.Column('initramfs_sub_path', sa.String(length=128), nullable=False),
    sa.Column('source_sub_path', sa.String(length=128), nullable=False),
    sa.Column('stage2_sub_path', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['bare_metal_image.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iso_sha256')
    )
    op.create_table('bare_metal_image_qcow2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_download_url', sa.String(length=1024), nullable=False),
    sa.Column('image_sha256', sa.String(length=64), nullable=False),
    sa.Column('kernel_download_url', sa.String(length=1024), nullable=False),
    sa.Column('kernel_sha256', sa.String(length=64), nullable=False),
    sa.Column('initramfs_download_url', sa.String(length=1024), nullable=False),
    sa.Column('initramfs_sha256', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['bare_metal_image.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_sha256'),
    sa.UniqueConstraint('initramfs_sha256'),
    sa.UniqueConstraint('kernel_sha256')
    )
    op.create_table('bare_metal_host',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('mac', sa.String(length=20), nullable=False),
    sa.Column('arch', sa.Enum('x86_64', name='baremetalarch'), nullable=False),
    sa.Column('legacy_bios', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('uefi', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('secure_boot', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'ENROLLING', 'FAILED_ENROLLING', 'MAINTENANCE', 'NON_ENROLLED', 'RESERVED', name='baremetalhoststatus'), server_default='NON_ENROLLED', nullable=False),
    sa.Column('type', sa.Enum('GENERIC', 'DRAC', 'REDFISH', name='baremetalhardwaretype'), nullable=False),
    sa.Column('handler_id', sa.Integer(), nullable=False),
    sa.Column('handler_uuid', postgresql.UUID(), nullable=True),
    sa.Column('handler_data', sa.JSON(), nullable=True),
    sa.Column('ipmi_address', sa.String(length=128), nullable=False),
    sa.Column('ipmi_password', sa.String(length=128), nullable=False),
    sa.Column('ipmi_port', sa.String(length=128), nullable=False),
    sa.Column('ipmi_username', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['handler_id'], ['bare_metal_handler.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bare_metal_host_drac',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('redfish_address', sa.String(length=128), nullable=True),
    sa.Column('redfish_password', sa.String(length=128), nullable=True),
    sa.Column('redfish_system_id', sa.String(length=128), nullable=True),
    sa.Column('redfish_username', sa.String(length=128), nullable=True),
    sa.Column('redfish_verify_ca', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('drac_address', sa.String(length=128), nullable=False),
    sa.Column('drac_username', sa.String(length=128), nullable=False),
    sa.Column('drac_password', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['bare_metal_host.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bare_metal_host_redfish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('redfish_address', sa.String(length=128), nullable=False),
    sa.Column('redfish_password', sa.String(length=128), nullable=False),
    sa.Column('redfish_system_id', sa.String(length=128), nullable=False),
    sa.Column('redfish_username', sa.String(length=128), nullable=False),
    sa.Column('redfish_verify_ca', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['bare_metal_host.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bare_metal_provision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('type', sa.Enum('GENERIC', 'ISO', 'QCOW2', name='baremetalprovisiontype'), nullable=False),
    sa.Column('boot_type', sa.Enum('LEGACY_BIOS', 'UEFI', 'SECURE_BOOT', name='baremetalboottype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'FAILED_PROVISIONING_DEPLOY_HOST', 'FAILED_PROVISIONING_SYNC_IMAGE', 'FAILED_RETURNING_HOST', 'FINISHED', 'PROVISIONING_DEPLOY_HOST', 'PROVISIONING_ENDING', 'PROVISIONING_SYNC_IMAGE', 'QUEUED', 'RETURNING_HOST', name='baremetalprovisionstatus'), server_default='QUEUED', nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('host_reservation_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('logs_path', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['bare_metal_host.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bare_metal_provision_iso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kickstart', sa.Text(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['bare_metal_provision.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['bare_metal_image_iso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bare_metal_provision_qcow2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['bare_metal_provision.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['bare_metal_image_qcow2.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bare_metal_provision_qcow2')
    op.drop_table('bare_metal_provision_iso')
    op.drop_table('bare_metal_provision')
    op.drop_table('bare_metal_host_redfish')
    op.drop_table('bare_metal_host_drac')
    op.drop_table('bare_metal_host')
    op.drop_table('bare_metal_image_qcow2')
    op.drop_table('bare_metal_image_iso')
    op.drop_table('bare_metal_handler')
    op.drop_table('bare_metal_image')
    # ### end Alembic commands ###
