version: 1
disable_existing_loggers: false

formatters:
  generic:
    format: '%(asctime)s - %(levelname)s %(name)s - %(message)s'
    datefmt: '%H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    level: NOTSET
    formatter: generic
  splunk:
    (): rhub.splunk_hec.SplunkHecHandler
    base_url: https://splunk-hec.example.com:8088
    token: 00000000-0000-0000-0000-000000000000
    source: rhub-prod
    sourcetype: openshift
    index: rhub
    fields: [name, pathname, lineno, funcName, module, levelno]

root:
  level: WARN
  handlers: [console]

loggers:
  werkzeug:  # flask wsgi
    level: INFO
  gunicorn:
    level: INFO
  sqlalchemy.engine:
    level: WARN
  alembic:
    level: INFO
  flask_migrate:
    level: INFO
  celery:
    level: INFO
  rhub:
    level: DEBUG
