version: 1
disable_existing_loggers: false

formatters:
  generic:
    format: '%(asctime)s - %(levelname)s %(name)s - %(message)s'
    datefmt: '%H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    level: NOTSET
    formatter: generic

root:
  level: WARN
  handlers: [console]

loggers:
  werkzeug:  # flask wsgi
    level: INFO
  gunicorn:
    level: INFO
  sqlalchemy.engine:
    level: WARN
  alembic:
    level: INFO
  flask_migrate:
    level: INFO
  celery:
    level: INFO
  rhub:
    level: DEBUG
