[ldap]
server = "ldap://ldap.example.com"
users_base = "ou=users,dc=example,dc=com"
# users_filter = "(objectClass=examplePerson)"
users_search = "(exampleUUID={})"
groups_base = "ou=groups,dc=example,dc=com"
# groups_filter = "(objectClass=exampleGroup)"

[ldap.user_attrs]
external_uuid = "uuid"
name = "uid"
email = "mail"
ssh_keys = "sshPublicKey"
manager = "manager"

[ldap.group_attrs]
name = "cn"

[messaging.email]
# Links at the bottom of notifications emails.
footer_links = [
  { title = "RHub UI", url = "https://rhub.example.com/" },
  { title = "RHub Documentation", url = "https://rhub-docs.example.com/" },
  { title = "RHub Support (Email)", url = "mailto:rhub-support@example.com" },
]
