[ldap]
server = "ldap://ldap.example.com"
users_base = "ou=users,dc=example,dc=com"
# users_filter = "(objectClass=examplePerson)"
users_search = "(exampleUUID={})"
groups_base = "ou=groups,dc=example,dc=com"
# groups_filter = "(objectClass=exampleGroup)"

[ldap.user_attrs]
external_uuid = "uuid"
name = "uid"
email = "mail"
ssh_keys = "sshPublicKey"
manager = "manager"

[ldap.group_attrs]
name = "cn"
