import os


KEYCLOAK_SERVER = os.getenv('KEYCLOAK_SERVER')
KEYCLOAK_RESOURCE = os.getenv('KEYCLOAK_RESOURCE')
KEYCLOAK_REALM = os.getenv('KEYCLOAK_REALM')
KEYCLOAK_SECRET = os.getenv('KEYCLOAK_SECRET')
KEYCLOAK_ADMIN_USER = os.getenv('KEYCLOAK_ADMIN_USER')
KEYCLOAK_ADMIN_PASS = os.getenv('KEYCLOAK_ADMIN_PASS')
