openapi: '3.0.2'
info:
  title: Resource Hub
  version: '0.1'

servers:
  - url: /v0

components:
  securitySchemes:
    basic:
      type: http
      scheme: basic
      x-basicInfoFunc: rhub.api.auth.security.basic_auth
    bearer:
      type: http
      scheme: bearer
      x-bearerInfoFunc: rhub.api.auth.security.bearer_auth

tags:
  - name: auth
    description: Authentication related functions.
  - name: lab
    description: Clusters for testing purposes.
  - name: openstack
    description: OpenStack clouds, projects, etc.
  - name: monitoring
    description: Internal monitoring functions.

paths:
  /cowsay:
    get:
      $ref: 'health.yml#/endpoints/cowsay'
  /ping:
    get:
      $ref: 'health.yml#/endpoints/ping'

  /openstack/cloud:
    get:
      $ref: 'openstack.yml#/endpoints/cloud_list'
    post:
      $ref: 'openstack.yml#/endpoints/cloud_create'
  /openstack/cloud/{cloud_id}:
    get:
      $ref: 'openstack.yml#/endpoints/cloud_get'
    patch:
      $ref: 'openstack.yml#/endpoints/cloud_update'
    delete:
      $ref: 'openstack.yml#/endpoints/cloud_delete'
  /openstack/project:
    get:
      $ref: 'openstack.yml#/endpoints/project_list'
    post:
      $ref: 'openstack.yml#/endpoints/project_create'
  /openstack/project/{project_id}:
    get:
      $ref: 'openstack.yml#/endpoints/project_get'
    patch:
      $ref: 'openstack.yml#/endpoints/project_update'
    delete:
      $ref: 'openstack.yml#/endpoints/project_delete'
  /openstack/project/{project_id}/limits:
    get:
      $ref: 'openstack.yml#/endpoints/project_limits_get'

  /satellite/server:
    get:
      $ref: 'satellite.yml#/endpoints/server_list'
    post:
      $ref: 'satellite.yml#/endpoints/server_create'
  /satellite/server/{server_id}:
    get:
      $ref: 'satellite.yml#/endpoints/server_get'
    patch:
      $ref: 'satellite.yml#/endpoints/server_update'
    delete:
      $ref: 'satellite.yml#/endpoints/server_delete'

  /dns/server:
    get:
      $ref: 'dns.yml#/endpoints/server_list'
    post:
      $ref: 'dns.yml#/endpoints/server_create'
  /dns/server/{server_id}:
    get:
      $ref: 'dns.yml#/endpoints/server_get'
    patch:
      $ref: 'dns.yml#/endpoints/server_update'
    delete:
      $ref: 'dns.yml#/endpoints/server_delete'

  /lab/location:
    get:
      $ref: 'lab.yml#/endpoints/location_list'
    post:
      $ref: 'lab.yml#/endpoints/location_create'
  /lab/location/{location_id}:
    get:
      $ref: 'lab.yml#/endpoints/location_get'
    patch:
      $ref: 'lab.yml#/endpoints/location_update'
    delete:
      $ref: 'lab.yml#/endpoints/location_delete'
  /lab/location/{location_id}/regions:
    get:
      $ref: 'lab.yml#/endpoints/location_region_list'
  /lab/region:
    get:
      $ref: 'lab.yml#/endpoints/region_list'
    post:
      $ref: 'lab.yml#/endpoints/region_create'
  /lab/region/{region_id}:
    get:
      $ref: 'lab.yml#/endpoints/region_get'
    patch:
      $ref: 'lab.yml#/endpoints/region_update'
    delete:
      $ref: 'lab.yml#/endpoints/region_delete'
  /lab/region/{region_id}/products:
    get:
      $ref: 'lab.yml#/endpoints/region_list_products'
    post:
      $ref: 'lab.yml#/endpoints/region_add_product'
    delete:
      $ref: 'lab.yml#/endpoints/region_remove_product'
  /lab/region/{region_id}/usage:
    get:
      $ref: 'lab.yml#/endpoints/region_get_usage'
  /lab/region/all/usage:
    get:
      $ref: 'lab.yml#/endpoints/region_get_all_usage'
  /lab/product:
    get:
      $ref: 'lab.yml#/endpoints/product_list'
    post:
      $ref: 'lab.yml#/endpoints/product_create'
  /lab/product/{product_id}:
    get:
      $ref: 'lab.yml#/endpoints/product_get'
    patch:
      $ref: 'lab.yml#/endpoints/product_update'
    delete:
      $ref: 'lab.yml#/endpoints/product_delete'
  /lab/product/{product_id}/regions:
    get:
      $ref: 'lab.yml#/endpoints/product_list_regions'
  /lab/cluster:
    get:
      $ref: 'lab.yml#/endpoints/cluster_list'
    post:
      $ref: 'lab.yml#/endpoints/cluster_create'
  /lab/cluster/{cluster_id}:
    get:
      $ref: 'lab.yml#/endpoints/cluster_get'
    patch:
      $ref: 'lab.yml#/endpoints/cluster_update'
    delete:
      $ref: 'lab.yml#/endpoints/cluster_delete'
  /lab/cluster/{cluster_id}/authorized_keys:
    get:
      $ref: 'lab.yml#/endpoints/cluster_authorized_keys'
  /lab/cluster/{cluster_id}/update:
    post:
      $ref: 'lab.yml#/endpoints/cluster_update_extra'
  /lab/cluster/{cluster_id}/events:
    get:
      $ref: 'lab.yml#/endpoints/cluster_list_events'
  /lab/cluster/{cluster_id}/hosts:
    get:
      $ref: 'lab.yml#/endpoints/cluster_hosts_list'
    post:
      $ref: 'lab.yml#/endpoints/cluster_hosts_create'
    delete:
      $ref: 'lab.yml#/endpoints/cluster_hosts_delete'
  /lab/cluster/{cluster_id}/reboot:
    post:
      $ref: 'lab.yml#/endpoints/cluster_reboot'
  /lab/cluster_event/{event_id}:
    get:
      $ref: 'lab.yml#/endpoints/cluster_event_get'
  /lab/cluster_event/{event_id}/stdout:
    get:
      $ref: 'lab.yml#/endpoints/cluster_event_get_stdout'

  /auth/user:
    get:
      $ref: 'auth.yml#/endpoints/user_list'
  /auth/user/{user_id}:
    get:
      $ref: 'auth.yml#/endpoints/user_get'
  /auth/user/{user_id}/ssh_keys:
    get:
      $ref: 'auth.yml#/endpoints/user_ssh_keys'
  /auth/user/{user_id}/token:
    get:
      $ref: 'auth.yml#/endpoints/token_list'
    post:
      $ref: 'auth.yml#/endpoints/token_create'
  /auth/user/{user_id}/token/{token_id}:
    delete:
      $ref: 'auth.yml#/endpoints/token_delete'
  /auth/group:
    get:
      $ref: 'auth.yml#/endpoints/group_list'
  /auth/group/{group_id}:
    get:
      $ref: 'auth.yml#/endpoints/group_get'
  /me:
    get:
      $ref: 'auth.yml#/endpoints/me'

  /tower/server:
    get:
      $ref: 'tower.yml#/endpoints/server_list'
    post:
      $ref: 'tower.yml#/endpoints/server_create'
  /tower/server/{server_id}:
    get:
      $ref: 'tower.yml#/endpoints/server_get'
    patch:
      $ref: 'tower.yml#/endpoints/server_update'
    delete:
      $ref: 'tower.yml#/endpoints/server_delete'
  /tower/template:
    get:
      $ref: 'tower.yml#/endpoints/template_list'
    post:
      $ref: 'tower.yml#/endpoints/template_create'
  /tower/template/{template_id}:
    get:
      $ref: 'tower.yml#/endpoints/template_get'
    patch:
      $ref: 'tower.yml#/endpoints/template_update'
    delete:
      $ref: 'tower.yml#/endpoints/template_delete'
  /tower/template/{template_id}/launch:
    post:
      $ref: 'tower.yml#/endpoints/template_launch'
  /tower/template/{template_id}/jobs:
    get:
      $ref: 'tower.yml#/endpoints/template_list_jobs'
  /tower/job:
    get:
      $ref: 'tower.yml#/endpoints/job_list'
  /tower/job/{job_id}:
    get:
      $ref: 'tower.yml#/endpoints/job_get'
  /tower/job/{job_id}/relaunch:
    post:
      $ref: 'tower.yml#/endpoints/job_relaunch'
  /tower/job/{job_id}/stdout:
    get:
      $ref: 'tower.yml#/endpoints/job_stdout'
  /tower/webhook_notification:
    post:
      $ref: 'tower.yml#/endpoints/webhook_notification'

  /policies:
    get:
      $ref: 'policy.yml#/endpoints/policy_list'
    post:
      $ref: 'policy.yml#/endpoints/policy_create'
  /policies/{policy_id}:
    get:
      $ref: 'policy.yml#/endpoints/policy_get'
    patch:
      $ref: 'policy.yml#/endpoints/policy_update'
    delete:
      $ref: 'policy.yml#/endpoints/policy_delete'

  /scheduler/cron:
    get:
      $ref: 'scheduler.yml#/endpoints/cron_job_list'
    post:
      $ref: 'scheduler.yml#/endpoints/cron_job_create'
  /scheduler/cron/{cron_job_id}:
    get:
      $ref: 'scheduler.yml#/endpoints/cron_job_get'
    patch:
      $ref: 'scheduler.yml#/endpoints/cron_job_update'
    delete:
      $ref: 'scheduler.yml#/endpoints/cron_job_delete'

  /monitor/bm/hosts/{host_type}:
    get:
      $ref: 'monitor.yml#/endpoints/bm_hosts_to_monitor_list'
  /monitor/bm/power_states_metrics:
    get:
      $ref: 'monitor.yml#/endpoints/bm_power_states_metrics_get'
  /monitor/bm/metrics:
    get:
      $ref: 'monitor.yml#/endpoints/bm_metrics_get'
  /monitor/vm/metrics:
    get:
      $ref: 'monitor.yml#/endpoints/vm_metrics_get'
  /monitor/lab/metrics:
    get:
      $ref: 'monitor.yml#/endpoints/lab_metrics_get'
