openapi: '3.0.2'
info:
  title: Resource Hub
  version: '0.1'

servers:
  - url: /v0

components:
  securitySchemes:
    basic:
      type: http
      scheme: basic
      x-basicInfoFunc: rhub.api.auth.token.basic_auth
    oauth2:
      type: http
      scheme: bearer
      bearerFormat: Bearer
      x-bearerInfoFunc: rhub.api.auth.token.decode_token
      x-tokenInfoFunc: rhub.api.auth.token.get_token_info
    tower_webhook_notification_auth:
      type: http
      scheme: basic
      x-basicInfoFunc: rhub.api.tower.webhook_auth

tags:
  - name: auth
    description: Authentication related functions.
  - name: bare_metal
    description: Bare metal related functions.
  - name: lab
    description: Clusters for testing purposes.
  - name: openstack
    description: OpenStack clouds, projects, etc.
  - name: monitoring
    description: Internal monitoring functions.

paths:
  /cowsay:
    get:
      $ref: 'health.yml#/endpoints/cowsay'
  /ping:
    get:
      $ref: 'health.yml#/endpoints/ping'

  /openstack/cloud:
    get:
      $ref: 'openstack.yml#/endpoints/cloud_list'
    post:
      $ref: 'openstack.yml#/endpoints/cloud_create'
  /openstack/cloud/{cloud_id}:
    get:
      $ref: 'openstack.yml#/endpoints/cloud_get'
    patch:
      $ref: 'openstack.yml#/endpoints/cloud_update'
    delete:
      $ref: 'openstack.yml#/endpoints/cloud_delete'
  /openstack/project:
    get:
      $ref: 'openstack.yml#/endpoints/project_list'
    post:
      $ref: 'openstack.yml#/endpoints/project_create'
  /openstack/project/{project_id}:
    get:
      $ref: 'openstack.yml#/endpoints/project_get'
    patch:
      $ref: 'openstack.yml#/endpoints/project_update'
    delete:
      $ref: 'openstack.yml#/endpoints/project_delete'
  /openstack/project/{project_id}/limits:
    get:
      $ref: 'openstack.yml#/endpoints/project_limits_get'

  /lab/location:
    get:
      $ref: 'lab.yml#/endpoints/location_list'
    post:
      $ref: 'lab.yml#/endpoints/location_create'
  /lab/location/{location_id}:
    get:
      $ref: 'lab.yml#/endpoints/location_get'
    patch:
      $ref: 'lab.yml#/endpoints/location_update'
    delete:
      $ref: 'lab.yml#/endpoints/location_delete'
  /lab/location/{location_id}/regions:
    get:
      $ref: 'lab.yml#/endpoints/location_region_list'
  /lab/region:
    get:
      $ref: 'lab.yml#/endpoints/region_list'
    post:
      $ref: 'lab.yml#/endpoints/region_create'
  /lab/region/{region_id}:
    get:
      $ref: 'lab.yml#/endpoints/region_get'
    patch:
      $ref: 'lab.yml#/endpoints/region_update'
    delete:
      $ref: 'lab.yml#/endpoints/region_delete'
  /lab/region/{region_id}/products:
    get:
      $ref: 'lab.yml#/endpoints/region_list_products'
    post:
      $ref: 'lab.yml#/endpoints/region_add_product'
    delete:
      $ref: 'lab.yml#/endpoints/region_remove_product'
  /lab/region/{region_id}/usage:
    get:
      $ref: 'lab.yml#/endpoints/region_get_usage'
  /lab/product:
    get:
      $ref: 'lab.yml#/endpoints/product_list'
    post:
      $ref: 'lab.yml#/endpoints/product_create'
  /lab/product/{product_id}:
    get:
      $ref: 'lab.yml#/endpoints/product_get'
    patch:
      $ref: 'lab.yml#/endpoints/product_update'
    delete:
      $ref: 'lab.yml#/endpoints/product_delete'
  /lab/product/{product_id}/regions:
    get:
      $ref: 'lab.yml#/endpoints/product_list_regions'
  /lab/cluster:
    get:
      $ref: 'lab.yml#/endpoints/cluster_list'
    post:
      $ref: 'lab.yml#/endpoints/cluster_create'
  /lab/cluster/{cluster_id}:
    get:
      $ref: 'lab.yml#/endpoints/cluster_get'
    patch:
      $ref: 'lab.yml#/endpoints/cluster_update'
    delete:
      $ref: 'lab.yml#/endpoints/cluster_delete'
  /lab/cluster/{cluster_id}/events:
    get:
      $ref: 'lab.yml#/endpoints/cluster_list_events'
  /lab/cluster/{cluster_id}/hosts:
    get:
      $ref: 'lab.yml#/endpoints/cluster_hosts_list'
    post:
      $ref: 'lab.yml#/endpoints/cluster_hosts_create'
    delete:
      $ref: 'lab.yml#/endpoints/cluster_hosts_delete'
  /lab/cluster/{cluster_id}/reboot:
    post:
      $ref: 'lab.yml#/endpoints/cluster_reboot'
  /lab/cluster_event/{event_id}:
    get:
      $ref: 'lab.yml#/endpoints/cluster_event_get'
  /lab/cluster_event/{event_id}/stdout:
    get:
      $ref: 'lab.yml#/endpoints/cluster_event_get_stdout'

  /auth/user:
    get:
      $ref: 'auth.yml#/endpoints/user_list'
    post:
      $ref: 'auth.yml#/endpoints/user_create'
  /auth/user/{user_id}:
    get:
      $ref: 'auth.yml#/endpoints/user_get'
    patch:
      $ref: 'auth.yml#/endpoints/user_update'
    delete:
      $ref: 'auth.yml#/endpoints/user_delete'
  /auth/user/{user_id}/groups:
    get:
      $ref: 'auth.yml#/endpoints/user_list_groups'
    post:
      $ref: 'auth.yml#/endpoints/user_add_group'
    delete:
      $ref: 'auth.yml#/endpoints/user_remove_group'
  /auth/user/{user_id}/roles:
    get:
      $ref: 'auth.yml#/endpoints/user_list_roles'
    post:
      $ref: 'auth.yml#/endpoints/user_add_role'
    delete:
      $ref: 'auth.yml#/endpoints/user_remove_role'
  /auth/group:
    get:
      $ref: 'auth.yml#/endpoints/group_list'
    post:
      $ref: 'auth.yml#/endpoints/group_create'
  /auth/group/{group_id}:
    get:
      $ref: 'auth.yml#/endpoints/group_get'
    patch:
      $ref: 'auth.yml#/endpoints/group_update'
    delete:
      $ref: 'auth.yml#/endpoints/group_delete'
  /auth/group/{group_id}/users:
    get:
      $ref: 'auth.yml#/endpoints/group_list_users'
  /auth/group/{group_id}/roles:
    get:
      $ref: 'auth.yml#/endpoints/group_list_roles'
    post:
      $ref: 'auth.yml#/endpoints/group_add_role'
    delete:
      $ref: 'auth.yml#/endpoints/group_remove_role'
  /auth/role:
    get:
      $ref: 'auth.yml#/endpoints/role_list'
    post:
      $ref: 'auth.yml#/endpoints/role_create'
  /auth/role/{role_id}:
    get:
      $ref: 'auth.yml#/endpoints/role_get'
    patch:
      $ref: 'auth.yml#/endpoints/role_update'
    delete:
      $ref: 'auth.yml#/endpoints/role_delete'
  /auth/token:
    get:
      $ref: 'auth.yml#/endpoints/token_get_info'
  /auth/token/create:
    post:
      $ref: 'auth.yml#/endpoints/token_create'
  /auth/token/refresh:
    post:
      $ref: 'auth.yml#/endpoints/token_refresh'
  /me:
    get:
      $ref: 'auth.yml#/endpoints/me'

  /tower/server:
    get:
      $ref: 'tower.yml#/endpoints/server_list'
    post:
      $ref: 'tower.yml#/endpoints/server_create'
  /tower/server/{server_id}:
    get:
      $ref: 'tower.yml#/endpoints/server_get'
    patch:
      $ref: 'tower.yml#/endpoints/server_update'
    delete:
      $ref: 'tower.yml#/endpoints/server_delete'
  /tower/template:
    get:
      $ref: 'tower.yml#/endpoints/template_list'
    post:
      $ref: 'tower.yml#/endpoints/template_create'
  /tower/template/{template_id}:
    get:
      $ref: 'tower.yml#/endpoints/template_get'
    patch:
      $ref: 'tower.yml#/endpoints/template_update'
    delete:
      $ref: 'tower.yml#/endpoints/template_delete'
  /tower/template/{template_id}/launch:
    post:
      $ref: 'tower.yml#/endpoints/template_launch'
  /tower/template/{template_id}/jobs:
    get:
      $ref: 'tower.yml#/endpoints/template_list_jobs'
  /tower/job:
    get:
      $ref: 'tower.yml#/endpoints/job_list'
  /tower/job/{job_id}:
    get:
      $ref: 'tower.yml#/endpoints/job_get'
  /tower/job/{job_id}/relaunch:
    post:
      $ref: 'tower.yml#/endpoints/job_relaunch'
  /tower/job/{job_id}/stdout:
    get:
      $ref: 'tower.yml#/endpoints/job_stdout'
  /tower/webhook_notification:
    post:
      $ref: 'tower.yml#/endpoints/webhook_notification'

  /policies:
    get:
      $ref: 'policy.yml#/endpoints/policy_list'
    post:
      $ref: 'policy.yml#/endpoints/policy_create'
  /policies/{policy_id}:
    get:
      $ref: 'policy.yml#/endpoints/policy_get'
    patch:
      $ref: 'policy.yml#/endpoints/policy_update'
    delete:
      $ref: 'policy.yml#/endpoints/policy_delete'

  /scheduler/cron:
    get:
      $ref: 'scheduler.yml#/endpoints/cron_job_list'
    post:
      $ref: 'scheduler.yml#/endpoints/cron_job_create'
  /scheduler/cron/{cron_job_id}:
    get:
      $ref: 'scheduler.yml#/endpoints/cron_job_get'
    patch:
      $ref: 'scheduler.yml#/endpoints/cron_job_update'
    delete:
      $ref: 'scheduler.yml#/endpoints/cron_job_delete'

  /monitor/bm/hosts:
    get:
      $ref: 'monitor.yml#/endpoints/bm_hosts_to_monitor_list'
  /monitor/bm/power_states_metrics:
    get:
      $ref: 'monitor.yml#/endpoints/bm_power_states_metrics_get'
  /monitor/bm/metrics:
    get:
      $ref: 'monitor.yml#/endpoints/bm_metrics_get'
  /monitor/vm/metrics:
    get:
      $ref: 'monitor.yml#/endpoints/vm_metrics_get'
  /monitor/lab/metrics:
    get:
      $ref: 'monitor.yml#/endpoints/lab_metrics_get'

  /bare_metal/handler:
    get:
      $ref: 'bare_metal.yml#/endpoints/handler_list'
    post:
      $ref: 'bare_metal.yml#/endpoints/handler_create'
  /bare_metal/handler/{handler_id}:
    get:
      $ref: 'bare_metal.yml#/endpoints/handler_get'

  /bare_metal/host:
    get:
      $ref: 'bare_metal.yml#/endpoints/host_list'
    post:
      $ref: 'bare_metal.yml#/endpoints/host_create'
  /bare_metal/host/{host_id}:
    get:
      $ref: 'bare_metal.yml#/endpoints/host_get'
  /bare_metal/host/{host_id}/power_state:
    get:
      $ref: 'bare_metal.yml#/endpoints/host_get_power_state'

  /bare_metal/image:
    get:
      $ref: 'bare_metal.yml#/endpoints/image_list'
    post:
      $ref: 'bare_metal.yml#/endpoints/image_create'
  /bare_metal/image/{image_id}:
    get:
      $ref: 'bare_metal.yml#/endpoints/image_get'

  /bare_metal/provision:
    get:
      $ref: 'bare_metal.yml#/endpoints/provision_list'
    post:
      $ref: 'bare_metal.yml#/endpoints/provision_create'
  /bare_metal/provision/{provision_id}:
    get:
      $ref: 'bare_metal.yml#/endpoints/provision_get'
  /bare_metal/provision/{provision_id}/finish:
    post:
      $ref: 'bare_metal.yml#/endpoints/provision_finish'
  /bare_metal/provision/{provision_id}/logs:
    post:
      $ref: 'bare_metal.yml#/endpoints/provision_logs_upload'
  /bare_metal/provision/{provision_id}/kickstart:
    get:
      $ref: 'bare_metal.yml#/endpoints/provision_get_kickstart'
  /bare_metal/provision/{provision_id}/kickstart/debug_script:
    get:
      $ref: 'bare_metal.yml#/endpoints/provision_kickstart_debug_script_get'
