name: Tox

on: [push, pull_request]

jobs:
  tox:
    runs-on: ubuntu-latest
    container: registry.access.redhat.com/ubi8/python-39

    strategy:
      matrix:
        toxenv: [py3, flake8, yamllint, openapi, package_build]

    steps:
      - uses: actions/checkout@v2
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e ${{ matrix.toxenv }}
