openapi: '3.0.2'
info:
  title: Resource Hub
  version: '0.1'

servers:
  - url: /v0

components:
  securitySchemes:
    basic:
      type: http
      scheme: basic
      x-basicInfoFunc: rhub.api.auth.token.basic_auth
    oauth2:
      type: http
      scheme: bearer
      bearerFormat: Bearer
      x-bearerInfoFunc: rhub.api.auth.token.decode_token
      x-tokenInfoFunc: rhub.api.auth.token.get_token_info
    tower_webhook_notification_auth:
      type: http
      scheme: basic
      x-basicInfoFunc: rhub.api.tower.webhook_auth

tags:
  - name: lab
    description: Clusters for testing purposes.
  - name: auth
    description: Authentication related functions.

paths:
  /cowsay:
    get:
      $ref: 'health.yml#/endpoints/cowsay'
  /ping:
    get:
      $ref: 'health.yml#/endpoints/ping'

  /lab/tower:
    get:
      $ref: 'lab.yml#/endpoints/tower_list'
    post:
      $ref: 'lab.yml#/endpoints/tower_create'
  /lab/tower/{tower_id}:
    get:
      $ref: 'lab.yml#/endpoints/tower_get'
    patch:
      $ref: 'lab.yml#/endpoints/tower_update'
    delete:
      $ref: 'lab.yml#/endpoints/tower_delete'
  /lab/region:
    get:
      $ref: 'lab.yml#/endpoints/region_list'
    post:
      $ref: 'lab.yml#/endpoints/region_create'
  /lab/region/{region_id}:
    get:
      $ref: 'lab.yml#/endpoints/region_get'
    patch:
      $ref: 'lab.yml#/endpoints/region_update'
    delete:
      $ref: 'lab.yml#/endpoints/region_delete'
  /lab/region/{region_id}/templates:
    get:
      $ref: 'lab.yml#/endpoints/region_list_templates'
    post:
      $ref: 'lab.yml#/endpoints/region_add_template'
    delete:
      $ref: 'lab.yml#/endpoints/region_remove_template'
  /lab/template:
    get:
      $ref: 'lab.yml#/endpoints/template_list'
    post:
      $ref: 'lab.yml#/endpoints/template_create'
  /lab/template/{template_id}:
    get:
      $ref: 'lab.yml#/endpoints/template_get'
    patch:
      $ref: 'lab.yml#/endpoints/template_update'
    delete:
      $ref: 'lab.yml#/endpoints/template_delete'
  /lab/template/{template_id}/bundles:
    get:
      $ref: 'lab.yml#/endpoints/template_list_bundles'
    post:
      $ref: 'lab.yml#/endpoints/template_add_bundle'
    delete:
      $ref: 'lab.yml#/endpoints/template_remove_bundle'
  /lab/bundle:
    get:
      $ref: 'lab.yml#/endpoints/bundle_list'
    post:
      $ref: 'lab.yml#/endpoints/bundle_create'
  /lab/bundle/{bundle_id}:
    get:
      $ref: 'lab.yml#/endpoints/bundle_get'
    patch:
      $ref: 'lab.yml#/endpoints/bundle_update'
    delete:
      $ref: 'lab.yml#/endpoints/bundle_delete'
  /lab/cluster:
    get:
      $ref: 'lab.yml#/endpoints/cluster_list'
    post:
      $ref: 'lab.yml#/endpoints/cluster_create'
  /lab/cluster/{cluster_id}:
    get:
      $ref: 'lab.yml#/endpoints/cluster_get'
    patch:
      $ref: 'lab.yml#/endpoints/cluster_update'
    delete:
      $ref: 'lab.yml#/endpoints/cluster_delete'

  /auth/user:
    get:
      $ref: 'auth.yml#/endpoints/user_list'
    post:
      $ref: 'auth.yml#/endpoints/user_create'
  /auth/user/{user_id}:
    get:
      $ref: 'auth.yml#/endpoints/user_get'
    patch:
      $ref: 'auth.yml#/endpoints/user_update'
    delete:
      $ref: 'auth.yml#/endpoints/user_delete'
  /auth/user/{user_id}/groups:
    get:
      $ref: 'auth.yml#/endpoints/user_list_groups'
    post:
      $ref: 'auth.yml#/endpoints/user_add_group'
    delete:
      $ref: 'auth.yml#/endpoints/user_remove_group'
  /auth/user/{user_id}/roles:
    get:
      $ref: 'auth.yml#/endpoints/user_list_roles'
    post:
      $ref: 'auth.yml#/endpoints/user_add_role'
    delete:
      $ref: 'auth.yml#/endpoints/user_remove_role'
  /auth/group:
    get:
      $ref: 'auth.yml#/endpoints/group_list'
    post:
      $ref: 'auth.yml#/endpoints/group_create'
  /auth/group/{group_id}:
    get:
      $ref: 'auth.yml#/endpoints/group_get'
    patch:
      $ref: 'auth.yml#/endpoints/group_update'
    delete:
      $ref: 'auth.yml#/endpoints/group_delete'
  /auth/group/{group_id}/users:
    get:
      $ref: 'auth.yml#/endpoints/group_list_users'
  /auth/group/{group_id}/roles:
    get:
      $ref: 'auth.yml#/endpoints/group_list_roles'
    post:
      $ref: 'auth.yml#/endpoints/group_add_role'
    delete:
      $ref: 'auth.yml#/endpoints/group_remove_role'
  /auth/role:
    get:
      $ref: 'auth.yml#/endpoints/role_list'
    post:
      $ref: 'auth.yml#/endpoints/role_create'
  /auth/role/{role_id}:
    get:
      $ref: 'auth.yml#/endpoints/role_get'
    patch:
      $ref: 'auth.yml#/endpoints/role_update'
    delete:
      $ref: 'auth.yml#/endpoints/role_delete'
  /auth/token:
    get:
      $ref: 'auth.yml#/endpoints/token_get_info'
  /auth/token/create:
    post:
      $ref: 'auth.yml#/endpoints/token_create'
  /auth/token/refresh:
    post:
      $ref: 'auth.yml#/endpoints/token_refresh'
  /me:
    get:
      $ref: 'auth.yml#/endpoints/me'

  /tower/server:
    get:
      $ref: 'tower.yml#/endpoints/server_list'
    post:
      $ref: 'tower.yml#/endpoints/server_create'
  /tower/server/{server_id}:
    get:
      $ref: 'tower.yml#/endpoints/server_get'
    patch:
      $ref: 'tower.yml#/endpoints/server_update'
    delete:
      $ref: 'tower.yml#/endpoints/server_delete'
  /tower/template:
    get:
      $ref: 'tower.yml#/endpoints/template_list'
    post:
      $ref: 'tower.yml#/endpoints/template_create'
  /tower/template/{template_id}:
    get:
      $ref: 'tower.yml#/endpoints/template_get'
    patch:
      $ref: 'tower.yml#/endpoints/template_update'
    delete:
      $ref: 'tower.yml#/endpoints/template_delete'
  /tower/template/{template_id}/launch:
    post:
      $ref: 'tower.yml#/endpoints/template_launch'
  /tower/template/{template_id}/jobs:
    get:
      $ref: 'tower.yml#/endpoints/template_list_jobs'
  /tower/job:
    get:
      $ref: 'tower.yml#/endpoints/job_list'
  /tower/job/{job_id}:
    get:
      $ref: 'tower.yml#/endpoints/job_get'
  /tower/job/{job_id}/relaunch:
    post:
      $ref: 'tower.yml#/endpoints/job_relaunch'
  /tower/job/{job_id}/stdout:
    get:
      $ref: 'tower.yml#/endpoints/job_stdout'
  /tower/webhook_notification:
    post:
      $ref: 'tower.yml#/endpoints/webhook_notification'

  /policies:
    get:
      $ref: 'policy.yml#/endpoints/policy_list'
    post:
      $ref: 'policy.yml#/endpoints/policy_create'
  /policies/{policy_id}:
    get:
      $ref: 'policy.yml#/endpoints/policy_get'
    patch:
      $ref: 'policy.yml#/endpoints/policy_update'
    delete:
      $ref: 'policy.yml#/endpoints/policy_delete'
  /policies/search:
    post:
      $ref: 'policy.yml#/endpoints/policy_search'
